### ISSUE TITLE
dead code

### ISSUE THREAD

**Issue by dpw** [squaremo/ambergreen#3]
Looks like we have obsolete and unused code from coatl under:

* `agent/alisten`
* `agent/listen`

And `agent/dlisten` just contains a README.

@squaremo can you confirm?

**Comment by squaremo** [comment]
Yeah those were experimental/demo code

**Comment by dpw** [comment]
Gone https://github.com/squaremo/ambergreen/commit/3d39377efdeac23a42415d8381f2e404bdf5530c
