### ISSUE TITLE
Docker image conflated with build completion

### ISSUE THREAD

**Issue by squaremo** [squaremo/ambergreen#4]
Our builds create a docker image, in general, but this is left on the docker server and a local file is touched to represent the build completion. In the case of using more than docker server, this means `make` will refuse to put the image on the server, which might be what one expects.

Suggestion: save the image from the docker server, and let that represent the built artefact. This also gives something that can be uploaded to other docker servers.

**Comment by dpw** [comment]
`docker save` for the application images yields a ~20MB tar file each.  But the build and webbuild images produce 700MB tar files.  That seems excessive.  Is it worth doing this for just the former but not the latter?

**Comment by squaremo** [comment]
Ugh, yeah that's a good point. Maybe the way to do it is with `make -W docker/Dockerfile.x` (assume the Dockerfile is new and build). This could be encoded as a rule `force-images`, though it'd have to call make recursively.

**Comment by dpw** [comment]
If you are just looking to upload the app images to some other docker host, isn't it fine to leave the build images un-saved?

**Comment by squaremo** [comment]
I guess it will at least fail to build, if the build images are not on the server.

**Comment by dpw** [comment]
https://github.com/squaremo/ambergreen/commit/0ad85c1c88abbcd6b7370dc7eb769416a451ac01

**Comment by squaremo** [comment]
Nice, thanks @dpw!
